name: 'packer-inspect'
author: 'Dawit Nida <dawit@dawitnida.com>'
description: 'Inspect packer template file in a directory'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-circle'
  color: 'green'